/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as EditorPageIdRouteImport } from './routes/editor.$pageId'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiFormsPageIdRouteImport } from './routes/api/forms/$pageId'
import { Route as ApiViewsPageIdRouteImport } from './routes/api/views/$pageId'
import { Route as PProjectSlugIndexRouteImport } from './routes/p/$projectSlug/index'
import { Route as PProjectSlugPageSlugRouteImport } from './routes/p/$projectSlug/$pageSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorPageIdRoute = EditorPageIdRouteImport.update({
  id: '/editor/$pageId',
  path: '/editor/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormsPageIdRoute = ApiFormsPageIdRouteImport.update({
  id: '/api/forms/$pageId',
  path: '/api/forms/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiViewsPageIdRoute = ApiViewsPageIdRouteImport.update({
  id: '/api/views/$pageId',
  path: '/api/views/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectSlugIndexRoute = PProjectSlugIndexRouteImport.update({
  id: '/p/$projectSlug/',
  path: '/p/$projectSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectSlugPageSlugRoute = PProjectSlugPageSlugRouteImport.update({
  id: '/p/$projectSlug/$pageSlug',
  path: '/p/$projectSlug/$pageSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/editor/$pageId': typeof EditorPageIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/forms/$pageId': typeof ApiFormsPageIdRoute
  '/api/views/$pageId': typeof ApiViewsPageIdRoute
  '/p/$projectSlug/$pageSlug': typeof PProjectSlugPageSlugRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/p/$projectSlug/': typeof PProjectSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/editor/$pageId': typeof EditorPageIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/forms/$pageId': typeof ApiFormsPageIdRoute
  '/api/views/$pageId': typeof ApiViewsPageIdRoute
  '/p/$projectSlug/$pageSlug': typeof PProjectSlugPageSlugRoute
  '/projects': typeof AppProjectsIndexRoute
  '/p/$projectSlug': typeof PProjectSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/editor/$pageId': typeof EditorPageIdRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/forms/$pageId': typeof ApiFormsPageIdRoute
  '/api/views/$pageId': typeof ApiViewsPageIdRoute
  '/p/$projectSlug/$pageSlug': typeof PProjectSlugPageSlugRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/p/$projectSlug/': typeof PProjectSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/editor/$pageId'
    | '/projects/$projectId'
    | '/api/auth/$'
    | '/api/forms/$pageId'
    | '/api/views/$pageId'
    | '/p/$projectSlug/$pageSlug'
    | '/projects/'
    | '/p/$projectSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/editor/$pageId'
    | '/projects/$projectId'
    | '/api/auth/$'
    | '/api/forms/$pageId'
    | '/api/views/$pageId'
    | '/p/$projectSlug/$pageSlug'
    | '/projects'
    | '/p/$projectSlug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/editor/$pageId'
    | '/_app/projects/$projectId'
    | '/api/auth/$'
    | '/api/forms/$pageId'
    | '/api/views/$pageId'
    | '/p/$projectSlug/$pageSlug'
    | '/_app/projects/'
    | '/p/$projectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  EditorPageIdRoute: typeof EditorPageIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFormsPageIdRoute: typeof ApiFormsPageIdRoute
  ApiViewsPageIdRoute: typeof ApiViewsPageIdRoute
  PProjectSlugPageSlugRoute: typeof PProjectSlugPageSlugRoute
  PProjectSlugIndexRoute: typeof PProjectSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$pageId': {
      id: '/editor/$pageId'
      path: '/editor/$pageId'
      fullPath: '/editor/$pageId'
      preLoaderRoute: typeof EditorPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forms/$pageId': {
      id: '/api/forms/$pageId'
      path: '/api/forms/$pageId'
      fullPath: '/api/forms/$pageId'
      preLoaderRoute: typeof ApiFormsPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/views/$pageId': {
      id: '/api/views/$pageId'
      path: '/api/views/$pageId'
      fullPath: '/api/views/$pageId'
      preLoaderRoute: typeof ApiViewsPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectSlug/': {
      id: '/p/$projectSlug/'
      path: '/p/$projectSlug'
      fullPath: '/p/$projectSlug/'
      preLoaderRoute: typeof PProjectSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectSlug/$pageSlug': {
      id: '/p/$projectSlug/$pageSlug'
      path: '/p/$projectSlug/$pageSlug'
      fullPath: '/p/$projectSlug/$pageSlug'
      preLoaderRoute: typeof PProjectSlugPageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  EditorPageIdRoute: EditorPageIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFormsPageIdRoute: ApiFormsPageIdRoute,
  ApiViewsPageIdRoute: ApiViewsPageIdRoute,
  PProjectSlugPageSlugRoute: PProjectSlugPageSlugRoute,
  PProjectSlugIndexRoute: PProjectSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
